### ISSUE TITLE
u-he plugins not receiving MIDI controller data

### ISSUE THREAD

**Issue by tas-from-planet-u-he** [free-audio/clap-wrapper#223]
Tested on M1 Sonoma in Bitwig 5.1.2 and Reaper 7.

Can be tested with the current Hive public beta revision 15319, found on KVR:
https://www.kvraudio.com/forum/viewtopic.php?t=603439

Using CLAP or the real VST3 version, everything works.
Using a CLAP wrapped VST3, I can play notes, and velocity and aftertouch are working.

But the plugin doesn't receive any MIDI controller data, no Mod Wheel, no Expression or any other controller number. It's not even receiving pitch bend data.

The plugins have a MIDI LED that blinks when it receives MIDI data. It's not lighting up when MIDI CC data is being sent to the plugin.

Not sure when this broke, it definitely already worked at some point, see my last comment in https://github.com/free-audio/clap-wrapper/issues/32

**Comment by baconpaul** [comment]
oh there's an opt in for midi ccs. i wonder if we made it default to nothing as opposed to everything. @defiantnerd - you remember that?

**Comment by defiantnerd** [comment]
Actually, the IMIDIMapping interfaces gets activated, if one of the CLAP MIDI input busses declares `CLAP_NOTE_DIALECT_MIDI` in the supported dialects.

Activation of the IMIDIMapping interface:
https://github.com/free-audio/clap-wrapper/blob/ae1841a9fea32630662d2b79b0554e33895e5e08/src/wrapasvst3.h#L172-L180

The check for support is here:

https://github.com/free-audio/clap-wrapper/blob/ae1841a9fea32630662d2b79b0554e33895e5e08/src/wrapasvst3.cpp#L52-L55
and here:
https://github.com/free-audio/clap-wrapper/blob/ae1841a9fea32630662d2b79b0554e33895e5e08/src/wrapasvst3.cpp#L499-L519

**Comment by u-he-frank** [comment]
Because _plugin->initialize() always returns true and kResultOk is 0, _useIMidiMapping will never be true.

https://github.com/free-audio/clap-wrapper/blob/ae1841a9fea32630662d2b79b0554e33895e5e08/src/wrapasvst3.cpp#L51-L55

But even if line 52 is changed to if (result == kResultOk),  _useIMidiMapping is already required to be set when calling ClapAsVst3::setupParameters in _plugin->initialize(), therefore it still doesn't work. Setting _useIMidiMapping in void ClapAsVst3::setupMIDIBusses does fix it, at least for me.

**Comment by defiantnerd** [comment]
You are completely correct - I'll fix that.

**Comment by defiantnerd** [comment]
fixed in 0.7.1

**Comment by tas-from-planet-u-he** [comment]
Checked with wrapper version 0.8.0. All MIDI CCs are working again in u-he plugins. Yay, thanks.
